### ISSUE TITLE
MemoryLeak

### ISSUE THREAD

**Issue by Buddelbubi** [GommeAWM/CPSCounter#1]
![grafik](https://user-images.githubusercontent.com/44944269/208592102-4939b352-92cc-4a84-b810-32e37578214d.png)

Do not use the player object as a key. Use the username instead. The player object contains just too much data like skin texture, geometry, location. Stuff that you do not want to fill your ram with. 

Also remove the player from the hashset weh the user quits. Otherwise the data will clumb up and may cause an overflow.

**Comment by GommeAWM** [comment]
Thank you for your help and contribution! I fixed the memory leak and posted an update on Cloudburst.
